# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'reloadable' do
  pod 'AppCenter/Crashes', '~> 1.14.0'
  pod 'AppCenter/Analytics', '~> 1.14.0'
  pod 'AppCenterReactNativeShared', '~> 1.13.0'
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for reloadable

  

  platform :ios, '9.0'
  pod 'CodePush', :path => '../node_modules/react-native-code-push'

  target 'reloadableTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'reloadable-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for reloadable-tvOS

  target 'reloadable-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
